In [14]:
import librosa
import numpy as np
from PIL import Image

def wav_to_spec_image(wav):
    """На вход принимает ссылку на wav
        на выходе сохраняет изображение спектрограммы и возвращает массив с плавающей точкой
    """
    audio_data = wav
    x , sr = librosa.load(audio_data)
    X = librosa.stft(x)
    Xdb = librosa.amplitude_to_db(abs(X))
    img = Image.fromarray(Xdb)
    img.save(f"{wav.split('.')[0]}.tiff", format="TIFF")
    print(f"Spec save like {wav.split('.')[0]}.tiff")
    return Xdb

def spec_to_image(filename, x):
    """
    На вход принимает название файла, который будет сохранён и массив спектрограммы.
    На выходе сохраняет файл и возвращает массив с плавающей точкой
    :param filename:
    :param x:
    :return:
    """
    X = librosa.stft(x)
    Xdb = librosa.amplitude_to_db(abs(X))
    img = Image.fromarray(Xdb)
    img.save(f"{filename}.tiff", format="TIFF")
    print(f"Spec save like {filename}.tiff")
    return Xdb

def image_to_audio_data(img):
    """
    Принимает изображение на вход. Возвращает массив спектрограммы с плавающей точкой.
    :param img:
    :return:
    """
    if type(img) == str:
        img = Image.open(img)
    img_array = np.asarray(img)
    return img_array

wav_to_spec_image("DuHast(бас).wav")

Spec save like DuHast(бас).tiff


array([[-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -14.155909 , -10.637502 ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -14.277291 , -10.641646 ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.706696 ,
        -14.3887005, -11.470326 ],
       ...,
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -33.80713  , -33.80713  ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -33.80713  , -33.80713  ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -33.80713  , -33.80713  ]], dtype=float32)

In [16]:
image_to_audio_data('DuHast(бас).tiff')

array([[-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -14.155909 , -10.637502 ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -14.277291 , -10.641646 ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.706696 ,
        -14.3887005, -11.470326 ],
       ...,
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -33.80713  , -33.80713  ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -33.80713  , -33.80713  ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -33.80713  , -33.80713  ]], dtype=float32)

In [17]:
test = Image.open('DuHast(бас).tiff')
image_to_audio_data(test)

array([[-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -14.155909 , -10.637502 ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -14.277291 , -10.641646 ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.706696 ,
        -14.3887005, -11.470326 ],
       ...,
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -33.80713  , -33.80713  ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -33.80713  , -33.80713  ],
       [-33.80713  , -33.80713  , -33.80713  , ..., -33.80713  ,
        -33.80713  , -33.80713  ]], dtype=float32)

In [10]:
test1= Image.fromarray(wav_to_spec_image("DuHast(бас).wav"))
test1.show()

Spec save like DuHast(бас).tiff
